version: "3.9"

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app/node:/app
    tty: true

  python:
    container_name: python
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 5000:5000
    volumes: 
      - ./app/python/:/app
    tty: true

  db:
    image: postgres:14
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'hash'
      POSTGRES_PASSWORD: 'password1234'

volumes:
  db-store:
